/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AppAlertType } from "./components/app-alert/app-alert";
export { AppAlertType } from "./components/app-alert/app-alert";
export namespace Components {
    interface AppAlert {
        /**
          * Controls the colour and icon used for the alert.
          * @default 'info'
         */
        "alertType": AppAlertType;
        /**
          * When true, renders a button that lets the user dismiss the alert.
          * @default false
         */
        "dismissible": boolean;
        /**
          * Optional heading shown above the slotted message.
         */
        "heading"?: string;
    }
}
export interface AppAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppAlertElement;
}
declare global {
    interface HTMLAppAlertElementEventMap {
        "appDismiss": void;
    }
    interface HTMLAppAlertElement extends Components.AppAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppAlertElementEventMap>(type: K, listener: (this: HTMLAppAlertElement, ev: AppAlertCustomEvent<HTMLAppAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppAlertElementEventMap>(type: K, listener: (this: HTMLAppAlertElement, ev: AppAlertCustomEvent<HTMLAppAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppAlertElement: {
        prototype: HTMLAppAlertElement;
        new (): HTMLAppAlertElement;
    };
    interface HTMLElementTagNameMap {
        "app-alert": HTMLAppAlertElement;
    }
}
declare namespace LocalJSX {
    interface AppAlert {
        /**
          * Controls the colour and icon used for the alert.
          * @default 'info'
         */
        "alertType"?: AppAlertType;
        /**
          * When true, renders a button that lets the user dismiss the alert.
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * Optional heading shown above the slotted message.
         */
        "heading"?: string;
        /**
          * Emitted after the user dismisses the alert.
         */
        "onAppDismiss"?: (event: AppAlertCustomEvent<void>) => void;
    }

    interface AppAlertAttributes {
        "alertType": AppAlertType;
        "heading": string;
        "dismissible": boolean;
    }

    interface IntrinsicElements {
        "app-alert": Omit<AppAlert, keyof AppAlertAttributes> & { [K in keyof AppAlert & keyof AppAlertAttributes]?: AppAlert[K] } & { [K in keyof AppAlert & keyof AppAlertAttributes as `attr:${K}`]?: AppAlertAttributes[K] } & { [K in keyof AppAlert & keyof AppAlertAttributes as `prop:${K}`]?: AppAlert[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-alert": LocalJSX.IntrinsicElements["app-alert"] & JSXBase.HTMLAttributes<HTMLAppAlertElement>;
        }
    }
}
